version: '2'
services:
    app:
        build:
            context: .test_yii/application
            args:
                - PATH_TO_PROJECT=/var/www/test_yii.app
        container_name: testyii.app
        volumes:
          - ./application:/var/www/test_yii.app
        tty: true
    nginx:
        build:
            context: .test_yii/nginx
        container_name: testyii_nginx
        volumes_from:
            - app
        volumes:
            - ./logs/nginx/:/var/log/nginx
        ports:
            - "80:80"
            - "443:443"
        links:
            - php-fpm
    php-fpm:
        build:
            context: .test_yii/php_fpm
        container_name: testyii_php-fpm
        volumes_from:
            - app
        expose:
            - "9000"
        links:
            - app
    mysql:
        build:
            context: .test_yii/mysql
        container_name: testyii_mysql
        volumes_from:
            - app
        ports:
            - "3306:3306"
        environment:
            MYSQL_DATABASE: sawfly
            MYSQL_USER: sawfly
            MYSQL_PASSWORD: secret
            MYSQL_ROOT_PASSWORD: root